---
title: "Data Science I: Homework 2"
author: "Nick Williams"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Problem 1

### Importing data

```{r importing data, collapse = TRUE}
nyc_transit_data <- read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

### NYC transit tidying

```{r tidying data, collapse = TRUE}
nyc_transit_data <- nyc_transit_data %>% 
  janitor::clean_names() %>% 
  select(line:entry, 
         vending, 
         ada) 

nyc_transit_data <- nyc_transit_data %>%
  gather(key = route_number, value = route_name, route1:route11) %>%
  separate(route_number,
           into = c("delete", "route_number"),
           sep = 5) %>%
  select(-delete)

nyc_transit_data$entry <- ifelse(nyc_transit_data$entry == "YES", TRUE, FALSE)
```

## Problem 2

### Importing Mr. Trash Wheel data 

```{r trash wheel import}
trash_wheel_data <- read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", 
                               sheet = "Mr. Trash Wheel", 
                               range = cell_cols("A:N")) 
```

### Tidying Mr. Trash Wheel

```{r trash wheel tidying}
trash_wheel_data <- trash_wheel_data %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(sports_balls))
```




